pipeline:
  name: test-neuraxle-public-release
  identifier: testneuraxlepublicrelease
  projectIdentifier: default
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: scm-connector
        repoName: neuraxle
        build: <+input>
  stages:
    - stage:
        identifier: Test_Python_Package
        type: CI
        name: Test Python Package
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: Install_dependencies
                  type: Run
                  name: Build and Test
                  spec:
                    connectorRef: account.harnessImage
                    image: python:3.6
                    shell: Sh
                    command: |-
                      python -m pip install --upgrade pip
                      pip install -r requirements.txt
                      python setup.py install

                      pip install flake8
                      # stop the build if there are Python syntax errors or undefined names
                      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                      # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                      flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics


                      python setup.py test
                  when:
                    stageStatus: All
                  failureStrategies: []
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        strategy:
          matrix:
            python:
              - 3.6
              - 3.7
              - 3.8
            maxConcurrency: 3
